#default: &default
#  adapter: mysql2
#  encoding: utf8
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: root
#  password: root
#  socket: /var/run/mysqld/mysqld.sock
#
#development:
#  <<: *default
#  database: phonebook_development
#
#test:
#  <<: *default
#  database: phonebook_test
#
#production:
#  <<: *default
#  database: phonebook_production
#  username: phonebook
#  password: <%= ENV['PHONEBOOK_DATABASE_PASSWORD'] %>

default: &default
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  
test:
  <<: *default
  
production:
  <<: *default  
