# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66dca219911b80ec9b036dba2ba02413171a2b3e2085a85901f60802016b3405767f3d5c8eee25f08b5e43f98e794d0357d39eb7f2031f2daf8716a85d137719

test:
  secret_key_base: 24123b8636693e2c70708c5fdf4512194a79775684892f9ccc63c7dd2cfaa8a374cd38995f44efec677a1831f7b3fb2876be19c6876a7e58dae21f8f22333262

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
